; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = arduino
lib_deps = 
    arduino-irremote/IRremote @ ^4.7.1
    olikraus/U8g2@^2.36.17   ; Display
    SDFat                    ; SD
    adafruit/RTClib @ ^2.1.1 ;

; Edge Impulse inferencing library points to exported Arduino library
; folder inside lib/. PlatformIO picks it up automatically from lib_extra_dirs.
lib_extra_dirs =
    lib

; Increase RAM available to the linker; the EI model + audio buffer are large.
board_build.partitions = huge_app.csv

; Build flags required by the Edge Impulse SDK on ESP32.
build_flags =
    -DEI_CLASSIFIER_TFLITE_ENABLE_ESP_NN=1   ; use Espressif's NN accelerator
    -DBOARD_HAS_PSRAM                         ; XIAO ESP32-S3 Sense has 8 MB PSRAM
    -mfix-esp32-psram-cache-issue             ; required when PSRAM is enabled